// Mocks generated by Mockito 5.4.2 from annotations
// in tv_series/test/presentation/pages/airing_today_tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/domain/domain.dart' as _i2;
import 'package:tv_series/presentation/cubit/airing_today_tv_series_cubit.dart'
    as _i4;
import 'package:tv_series/presentation/cubit/base_state.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAiringTodayTvSeries_0 extends _i1.SmartFake
    implements _i2.GetAiringTodayTvSeries {
  _FakeGetAiringTodayTvSeries_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseState_1<T> extends _i1.SmartFake implements _i3.BaseState<T> {
  _FakeBaseState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AiringTodayTvSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiringTodayTvSeriesCubit extends _i1.Mock
    implements _i4.AiringTodayTvSeriesCubit {
  @override
  _i2.GetAiringTodayTvSeries get getAiringTodayTvSeries => (super.noSuchMethod(
        Invocation.getter(#getAiringTodayTvSeries),
        returnValue: _FakeGetAiringTodayTvSeries_0(
          this,
          Invocation.getter(#getAiringTodayTvSeries),
        ),
        returnValueForMissingStub: _FakeGetAiringTodayTvSeries_0(
          this,
          Invocation.getter(#getAiringTodayTvSeries),
        ),
      ) as _i2.GetAiringTodayTvSeries);
  @override
  _i3.BaseState<List<_i2.TvSeries>> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBaseState_1<List<_i2.TvSeries>>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeBaseState_1<List<_i2.TvSeries>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.BaseState<List<_i2.TvSeries>>);
  @override
  _i5.Stream<_i3.BaseState<List<_i2.TvSeries>>> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.BaseState<List<_i2.TvSeries>>>.empty(),
        returnValueForMissingStub:
            _i5.Stream<_i3.BaseState<List<_i2.TvSeries>>>.empty(),
      ) as _i5.Stream<_i3.BaseState<List<_i2.TvSeries>>>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void get() => super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i3.BaseState<List<_i2.TvSeries>>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i3.BaseState<List<_i2.TvSeries>>>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
