// Mocks generated by Mockito 5.4.2 from annotations
// in tv_series/test/presentation/pages/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/domain/domain.dart' as _i2;
import 'package:tv_series/presentation/cubit/base_state.dart' as _i3;
import 'package:tv_series/presentation/cubit/tv_series_detail_cubit.dart'
    as _i4;
import 'package:tv_series/presentation/cubit/tv_series_watchlist_action_cubit.dart'
    as _i8;
import 'package:tv_series/presentation/cubit/tv_series_watchlist_status_cubit.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTvSeriesDetail {
  _FakeGetTvSeriesDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesRecommendations_1 extends _i1.SmartFake
    implements _i2.GetTvSeriesRecommendations {
  _FakeGetTvSeriesRecommendations_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseState_2<T> extends _i1.SmartFake implements _i3.BaseState<T> {
  _FakeBaseState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListTvSeriesStatus_3 extends _i1.SmartFake
    implements _i2.GetWatchListTvSeriesStatus {
  _FakeGetWatchListTvSeriesStatus_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTvSeries_4 extends _i1.SmartFake
    implements _i2.SaveWatchlistTvSeries {
  _FakeSaveWatchlistTvSeries_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTvSeries_5 extends _i1.SmartFake
    implements _i2.RemoveWatchlistTvSeries {
  _FakeRemoveWatchlistTvSeries_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesDetailCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailCubit extends _i1.Mock
    implements _i4.TvSeriesDetailCubit {
  @override
  _i2.GetTvSeriesDetail get getTvSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesDetail),
        returnValue: _FakeGetTvSeriesDetail_0(
          this,
          Invocation.getter(#getTvSeriesDetail),
        ),
        returnValueForMissingStub: _FakeGetTvSeriesDetail_0(
          this,
          Invocation.getter(#getTvSeriesDetail),
        ),
      ) as _i2.GetTvSeriesDetail);
  @override
  _i2.GetTvSeriesRecommendations get getTvSeriesRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getTvSeriesRecommendations),
        returnValue: _FakeGetTvSeriesRecommendations_1(
          this,
          Invocation.getter(#getTvSeriesRecommendations),
        ),
        returnValueForMissingStub: _FakeGetTvSeriesRecommendations_1(
          this,
          Invocation.getter(#getTvSeriesRecommendations),
        ),
      ) as _i2.GetTvSeriesRecommendations);
  @override
  _i3.BaseState<_i2.TvSeriesDetail> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBaseState_2<_i2.TvSeriesDetail>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeBaseState_2<_i2.TvSeriesDetail>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.BaseState<_i2.TvSeriesDetail>);
  @override
  _i5.Stream<_i3.BaseState<_i2.TvSeriesDetail>> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.BaseState<_i2.TvSeriesDetail>>.empty(),
        returnValueForMissingStub:
            _i5.Stream<_i3.BaseState<_i2.TvSeriesDetail>>.empty(),
      ) as _i5.Stream<_i3.BaseState<_i2.TvSeriesDetail>>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void get({required int? id}) => super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i3.BaseState<_i2.TvSeriesDetail>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i3.BaseState<_i2.TvSeriesDetail>>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TvSeriesWatchlistStatusCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesWatchlistStatusCubit extends _i1.Mock
    implements _i7.TvSeriesWatchlistStatusCubit {
  @override
  _i2.GetWatchListTvSeriesStatus get getWatchListTvSeriesStatus =>
      (super.noSuchMethod(
        Invocation.getter(#getWatchListTvSeriesStatus),
        returnValue: _FakeGetWatchListTvSeriesStatus_3(
          this,
          Invocation.getter(#getWatchListTvSeriesStatus),
        ),
        returnValueForMissingStub: _FakeGetWatchListTvSeriesStatus_3(
          this,
          Invocation.getter(#getWatchListTvSeriesStatus),
        ),
      ) as _i2.GetWatchListTvSeriesStatus);
  @override
  bool get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i5.Stream<bool> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<bool>.empty(),
        returnValueForMissingStub: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void get({required int? id}) => super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(bool? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<bool>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TvSeriesWatchlistActionCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesWatchlistActionCubit extends _i1.Mock
    implements _i8.TvSeriesWatchlistActionCubit {
  @override
  _i2.SaveWatchlistTvSeries get saveWatchlistTvSeries => (super.noSuchMethod(
        Invocation.getter(#saveWatchlistTvSeries),
        returnValue: _FakeSaveWatchlistTvSeries_4(
          this,
          Invocation.getter(#saveWatchlistTvSeries),
        ),
        returnValueForMissingStub: _FakeSaveWatchlistTvSeries_4(
          this,
          Invocation.getter(#saveWatchlistTvSeries),
        ),
      ) as _i2.SaveWatchlistTvSeries);
  @override
  _i2.RemoveWatchlistTvSeries get removeWatchlistTvSeries =>
      (super.noSuchMethod(
        Invocation.getter(#removeWatchlistTvSeries),
        returnValue: _FakeRemoveWatchlistTvSeries_5(
          this,
          Invocation.getter(#removeWatchlistTvSeries),
        ),
        returnValueForMissingStub: _FakeRemoveWatchlistTvSeries_5(
          this,
          Invocation.getter(#removeWatchlistTvSeries),
        ),
      ) as _i2.RemoveWatchlistTvSeries);
  @override
  _i3.BaseState<String> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBaseState_2<String>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeBaseState_2<String>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.BaseState<String>);
  @override
  _i5.Stream<_i3.BaseState<String>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.BaseState<String>>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.BaseState<String>>.empty(),
      ) as _i5.Stream<_i3.BaseState<String>>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void add({required _i2.TvSeriesDetail? detail}) => super.noSuchMethod(
        Invocation.method(
          #add,
          [],
          {#detail: detail},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void remove({required int? id}) => super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i3.BaseState<String>? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i3.BaseState<String>>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
